integrations:
- name: nri-jmx
  env:
    COLLECTION_FILES: "/etc/newrelic-infra/integrations.d/jvm-metrics.yml,/etc/newrelic-infra/integrations.d/tomcat-metrics.yml"
    JMX_HOST: jmx-host.localnet
    JMX_PASS: admin
    JMX_PORT: "1234"
    JMX_USER: admin

    # New users should leave this property as `true`, to identify the
    # monitored entities as `remote`. Setting this property to `false` (the
    # default value) is deprecated and will be removed soon, disallowing
    # entities that are identified as `local`.
    # Please check the documentation to get more information about local
    # versus remote entities:
    # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
    REMOTE_MONITORING: "true"
  interval: 15s
  labels:
    env: staging
